# Generated by Django 5.0.4 on 2024-04-15 12:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='billing_code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='production',
            name='production_code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='billing',
            unique_together={('billing_code',)},
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('cart_code',)},
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('customer_code',)},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('order_code',)},
        ),
        migrations.AlterUniqueTogether(
            name='production',
            unique_together={('production_code',)},
        ),
        migrations.AlterUniqueTogether(
            name='shipping',
            unique_together={('shipping_code',)},
        ),
    ]
